settings:
  docker:
    parent_image: pytorch/pytorch:2.3.1-cuda12.1-cudnn8-devel
    environment:
      ZENML_LOGGING_COLORS_DISABLED: true
    requirements:
      - zenml==0.68.1
      - transformers==4.46.3
      - lightning==2.3
      - pytorch-metric-learning==2.4.1
      - tensorboard==2.16.2
      - pyarrow==15.0.1

parameters:
  dataset_id: gs://<google-cloud-project-id>-data/data/df_sampled.parquet
  split_ids: c6612eac-ecd2-46fa-9a26-15e78a6b6c39

steps:
  transcribe:
    parameters:
      source_separation_config:
        c_status: source_separation_status_spleeter
        c_vocals: vocals_spleeter

  train:
    parameters:
      base_model: jinaai/jina-embeddings-v2-small-en
      max_epochs: 1
      batch_size: 128
      margin: 2
      patience_early_stopping: 5
      lr_reduce_patience: 3
      min_delta_early_stopping: 0.01
      trainable_layers:
        - encoder.layer.3
        - pooler
  evaluate:
    parameters:
      batch_size: 8
